config/routes.rb
Cabbeen::Application.routes.draw do

  root :to => "home#index"

  def api_v1_routes
    namespace :v1 do
      resources :brand_info, :only => :index
      resources :city_weeklies, :only => :index
      resources :launch, :only => :create
      resources :lastest_see, :only => :index
      resources :products, :only => [:index, :show]
      resources :product_comments, :only => :create
      resources :shop_info, :only => :index
      resources :suits, :only => :index do
        collection do
          get 'search'
        end
      end
      resources :trend_couriers, :only => [:index, :show]
      resources :skins, :only => [:show, :index]
      resources :names, :only => [:index]
    end
  end

  def admin_routes

    devise_for :admins

    match '/admin' => redirect('/admins/sign_in')

    namespace :admin do

      resources :admins do
        collection do
          get 'edit_pwd' => 'admins#edit_pwd'
          put 'edit_pwd' => 'admins#update_pwd'
        end
      end

      resources :ads
      resources :brands
      resources :categories do
        resources :products
        collection do
          post 'modify/:id' => 'categories#modify'
        end
      end
      resources :city_weeklies do
        collection do
          get 'export'
        end
      end
      resources :dashboard, :only => :index
      resources :latest_sees do
        resources :pictures, :controller => :latest_see_pictures do
          collection do
            post 'modify/:id' => 'latest_see_pictures#modify'
          end
        end
        collection do
          get 'export'
        end
      end
      resources :new_products do
        resources :suits
        collection do
          post 'modify/:id' => 'new_products#modify'
          get 'export'
        end
      end
      resources :products do
        resources :comments, :controller => :product_comments
        resources :pictures, :controller => :product_pictures do
          collection do
            post 'modify/:id' => 'product_pictures#modify'
          end
        end
        resources :same_sections, :controller => :product_same_sections

        collection do
          get 'export'
          get 'export_comment' => 'product_comments#export'
          post 'batch_listed'
          post 'batch_unlisted'
          post 'batch_destroy'
          post 'batch_same_section'
          post 'modify/:id' => 'products#modify'
        end

      end
      get 'products_comments' => 'product_comments#index'

      resources :shop_infos
      resources :suits do
        collection do
          post 'modify/:id' => 'suits#modify'
          get 'export'
        end
        resources :products
      end

      resources :skins
      resources :trend_couriers do
        resources :products
        collection do
          get 'export'
        end
      end
    end
  end

  api_v1_routes
  admin_routes

end

app/models/trend_courier.rb
class TrendCourier < ActiveRecord::Base
  attr_accessible :title, :pic, :status

  has_many :products

  validates_presence_of :pic

  mount_uploader :pic, PictureUploader

  def simple_json
    {
        pic: self.full_pic_url,
        title: Cat::Tool.nil2n(self.title)
    }
  end

  def full_pic_url
    if self.pic and self.pic.url
      Rails.application.config.action_controller.asset_host + self.pic.url
    else
      ''
    end
  end

end

app/controllers/admin/trend_couriers_controller.rb
class Admin::TrendCouriersController < Admin::BaseController
  load_and_authorize_resource

  def index
    @trend_couriers = initialize_grid(TrendCourier, order: 'id', order_direction: 'desc')
  end

  def create
    @trend_courier = TrendCourier.new(params[:trend_courier])
    if @trend_courier.save
      create_successfully
      redirect_to action: :index
    else
      fail_to_create
      render action: :new
    end
  end

  def update
    @trend_courier = TrendCourier.find_by_id(params[:id])
    if @trend_courier.update_attributes(params[:trend_courier])
      update_successfully
      redirect_to action: :show
    else
      fail_to_update
      render action: :edit
    end
  end

  def destroy
    @trend_courier = TrendCourier.find_by_id(params[:id])
    if @trend_courier.destroy
      destroy_successfully
    else
      fail_to_destroy
    end
    redirect_to action: :index
  end


  def export
    authorize! :update, TrendCourier
    respond_to do |format|
      format.html {

      }
      format.xlsx {
        @created_from = Cat::Tool.to_date(params[:from])
        @created_from = Date.today - 30.days if @created_from.nil?
        @created_to = Cat::Tool.to_date(params[:to], true)
        @trend_couriers = TrendCourier.where('created_at >= ? and created_at < ?', @created_from.to_time.utc, (@created_to + 1.day).to_time.utc).order('id desc').all
        render xlsx: 'export', disposition: "attachment", layout: false, filename: "trend_courier_#{@created_from}_#{@created_to}"
      }
    end
  end
end

app/views/admin/trend_couriers/_form.slim
- admin_left_menu :trend_courier
.page-header
  h4= title @trend_courier.new_record? ? '添加潮流速递' : "修改潮流速递 #{@trend_courier.title}"
.action-buttons
  - if @trend_courier.id
    = link_to '<i class="icon-th-large icon-white"></i>'.html_safe, admin_trend_courier_products_path(@trend_courier), class: 'btn btn-primary', title: '单品'
    = actions_buttons(@trend_courier, 5)

= simple_form_for @trend_courier, :url => (@trend_courier.new_record? ? admin_trend_couriers_path : admin_trend_courier_path(@trend_courier)), :html => {class: 'form-horizontal'} do |f|
  fieldset
    = f.input :title
    = f.input :pic
    = f.input :status
    .form-actions
      = f.submit (@trend_courier.new_record? ? '保存' : '修改') , class: 'btn btn-primary', disable_with: '上传中，请稍等...'
- unless @trend_courier.new_record?
  h5 潮流速递图标预览:
  p= image_tag(@trend_courier.pic.url)

app/views/admin/trend_couriers/_grid.html.erb
<%= grid(@trend_couriers, :show_filters => :when_filtered, :allow_showing_all_records => false, class: 'table-img') do |g|

  g.column do |obj|
    link_to(image_tag(obj.pic.thumb.url), obj.pic.url, target: '_blank') if obj.pic.url
  end

  %w(id title status created_at updated_at).each do |attr|
    g.column :name => TrendCourier.human_attribute_name(attr.to_sym), :attribute => attr do |obj|
      if attr.in? %w(created_at updated_at)
        t2l(obj.send(attr.to_sym))
      elsif attr == 'status'
        status_icon(obj.status)
      else
        obj.send(attr.to_sym)
      end
    end
  end

  g.column do |obj|
    link = link_to '<i class="icon-th-large"></i>'.html_safe, admin_trend_courier_products_path(obj), title: '单品'
    link << actions_links(obj, 7)
  end
end -%>

app/views/admin/trend_couriers/edit.slim
= trend_courier_breadcrumb @trend_courier
= render 'form'

app/views/admin/trend_couriers/export.slim
- admin_left_menu :trend_courier
.page-header
  h4 导出潮流速递数据

div
  form action="#{export_admin_trend_couriers_path('xlsx')}" method="get" class="form-inline"
    p 根据潮流速递创建的时间来导出数据。请选择创建时间：
    p
      | 从：
      input type="text" class="input-small" name="from" id="from"
      | &nbsp;&nbsp;到：
      input type="text" class="input-small" name="to" id="to"
      | &nbsp;&nbsp;&nbsp;&nbsp;
      button type="submit" class="btn btn-primary" 导出
- content_for :footer do
  javascript:
    $(document).ready(function(){el.Tool.datePicker();});

app/views/admin/trend_couriers/index.slim
- admin_left_menu :trend_courier
.page-header
  h4= title '潮流速递管理'
= render :partial => 'grid'

app/views/admin/trend_couriers/show.slim
- title "潮流速递-#{@trend_courier.title}"
- admin_left_menu :trend_courier
= trend_courier_breadcrumb @trend_courier
.action-buttons
  = link_to '<i class="icon-th-large icon-white"></i>'.html_safe, admin_trend_courier_products_path(@trend_courier), class: 'btn btn-primary', title: '单品'
  = actions_buttons(@trend_courier, 6)
table class="table table-striped"
  - TrendCourier.attribute_names.each do |attr_name|
    tr
      th= TrendCourier.human_attribute_name(attr_name)
      td
        - if 'pic' == attr_name
          = @trend_courier.pic.url.blank? ? '' : link_to(image_tag(@trend_courier.pic.thumb.url), @trend_courier.pic.url, target: '_blank')
        - elsif attr_name.in?(%w(created_at updated_at))
          = t2l(@trend_courier.send(attr_name.to_sym))
        - else
          = @trend_courier.send(attr_name.to_sym)