config/routes.rb
Cabbeen::Application.routes.draw do

  root :to => "home#index"

  def api_v1_routes
    namespace :v1 do
      resources :brand_info, :only => :index
      resources :city_weeklies, :only => :index
      resources :launch, :only => :create
      resources :lastest_see, :only => :index
      resources :products, :only => [:index, :show]
      resources :product_comments, :only => :create
      resources :shop_info, :only => :index
      resources :suits, :only => :index do
        collection do
          get 'search'
        end
      end
      resources :trend_couriers, :only => [:index, :show]
      resources :skins, :only => [:show, :index]
      resources :names, :only => [:index]
    end
  end

  def admin_routes

    devise_for :admins

    match '/admin' => redirect('/admins/sign_in')

    namespace :admin do

      resources :admins do
        collection do
          get 'edit_pwd' => 'admins#edit_pwd'
          put 'edit_pwd' => 'admins#update_pwd'
        end
      end

      resources :ads
      resources :brands
      resources :categories do
        resources :products
        collection do
          post 'modify/:id' => 'categories#modify'
        end
      end
      resources :city_weeklies do
        collection do
          get 'export'
        end
      end
      resources :dashboard, :only => :index
      resources :latest_sees do
        resources :pictures, :controller => :latest_see_pictures do
          collection do
            post 'modify/:id' => 'latest_see_pictures#modify'
          end
        end
        collection do
          get 'export'
        end
      end
      resources :new_products do
        resources :suits
        collection do
          post 'modify/:id' => 'new_products#modify'
          get 'export'
        end
      end
      resources :products do
        resources :comments, :controller => :product_comments
        resources :pictures, :controller => :product_pictures do
          collection do
            post 'modify/:id' => 'product_pictures#modify'
          end
        end
        resources :same_sections, :controller => :product_same_sections

        collection do
          get 'export'
          get 'export_comment' => 'product_comments#export'
          post 'batch_listed'
          post 'batch_unlisted'
          post 'batch_destroy'
          post 'batch_same_section'
          post 'modify/:id' => 'products#modify'
        end

      end
      get 'products_comments' => 'product_comments#index'

      resources :shop_infos
      resources :suits do
        collection do
          post 'modify/:id' => 'suits#modify'
          get 'export'
        end
        resources :products
      end

      resources :skins
      resources :trend_couriers do
        resources :products
        collection do
          get 'export'
        end
      end
    end
  end

  api_v1_routes
  admin_routes

end

app/views/admin/admins/_grid.html.erb
<%= grid(@admins, :show_filters => :when_filtered, :allow_showing_all_records => false) do |g|
  %w(id name email sign_in_count last_sign_in_at last_sign_in_ip).each do |attr|
    g.column :name => Admin.human_attribute_name(attr.to_sym), :attribute => attr do |user|
      if attr == 'last_sign_in_at'
        t2l(user.send(attr.to_sym))
      else
        user.send(attr.to_sym)
      end
    end
  end

  g.column do |user|
    actions_links user, 6
  end
end -%>

app/views/admin/admins/edit.slim
- admin_left_menu :admin
.page-header
  h4= title "修改管理员 #{@admin.name}"
  .action-buttons
    = actions_buttons(@admin, 4)
= simple_form_for @admin, :url => admin_admin_path(@admin), :html => {class: 'form-horizontal'} do |f|
  fieldset
    = f.input :name
    = f.input :email
    = f.input :role, collection: Admin.roles, as: :radio
    .form-actions
      = f.submit '修改' , class: 'btn btn-primary'

app/views/admin/admins/edit_pwd.slim
- admin_left_menu :admin
= simple_form_for current_admin, :url => edit_pwd_admin_admins_path, :method => :put, :html => {class: 'form-horizontal'} do |f|
  fieldset
    legend= title '修改密码'
    = f.input :email, required: true
    = f.input :password, required: true
    = f.input :password_confirmation, required: true
    = f.input :current_password, required: true
    .form-actions
      = f.submit '确认', class: 'btn btn-primary'

app/views/admin/admins/index.slim
- admin_left_menu :admin
.page-header
  h4= title '管理员管理'
= render :partial => 'grid'

app/views/admin/admins/new.slim
- admin_left_menu :admin
.page-header
  h4= title '添加管理员'
= simple_form_for @admin, :url => admin_admins_path, :html => {class: 'form-horizontal', autocomplete: 'off'} do |f|
  fieldset
    = f.input :name
    = f.input :email
    = f.input :password
    = f.input :password_confirmation
    = f.input :role, collection: Admin.roles_human, as: :hidden
    .form-actions
      = f.submit '添加' , class: 'btn btn-primary'