config/routes.rb
Cabbeen::Application.routes.draw do

  root :to => "home#index"

  def api_v1_routes
    namespace :v1 do
      resources :brand_info, :only => :index
      resources :city_weeklies, :only => :index
      resources :launch, :only => :create
      resources :lastest_see, :only => :index
      resources :products, :only => [:index, :show]
      resources :product_comments, :only => :create
      resources :shop_info, :only => :index
      resources :suits, :only => :index do
        collection do
          get 'search'
        end
      end
      resources :trend_couriers, :only => [:index, :show]
      resources :skins, :only => [:show, :index]
      resources :names, :only => [:index]
    end
  end

  def admin_routes

    devise_for :admins

    match '/admin' => redirect('/admins/sign_in')

    namespace :admin do

      resources :admins do
        collection do
          get 'edit_pwd' => 'admins#edit_pwd'
          put 'edit_pwd' => 'admins#update_pwd'
        end
      end

      resources :ads
      resources :brands
      resources :categories do
        resources :products
        collection do
          post 'modify/:id' => 'categories#modify'
        end
      end
      resources :city_weeklies do
        collection do
          get 'export'
        end
      end
      resources :dashboard, :only => :index
      resources :latest_sees do
        resources :pictures, :controller => :latest_see_pictures do
          collection do
            post 'modify/:id' => 'latest_see_pictures#modify'
          end
        end
        collection do
          get 'export'
        end
      end
      resources :new_products do
        resources :suits
        collection do
          post 'modify/:id' => 'new_products#modify'
          get 'export'
        end
      end
      resources :products do
        resources :comments, :controller => :product_comments
        resources :pictures, :controller => :product_pictures do
          collection do
            post 'modify/:id' => 'product_pictures#modify'
          end
        end
        resources :same_sections, :controller => :product_same_sections

        collection do
          get 'export'
          get 'export_comment' => 'product_comments#export'
          post 'batch_listed'
          post 'batch_unlisted'
          post 'batch_destroy'
          post 'batch_same_section'
          post 'modify/:id' => 'products#modify'
        end

      end
      get 'products_comments' => 'product_comments#index'

      resources :shop_infos
      resources :suits do
        collection do
          post 'modify/:id' => 'suits#modify'
          get 'export'
        end
        resources :products
      end

      resources :skins
      resources :trend_couriers do
        resources :products
        collection do
          get 'export'
        end
      end
    end
  end

  api_v1_routes
  admin_routes

end

app/models/new_product.rb
class NewProduct < ActiveRecord::Base
  attr_accessible :name, :pic, :rank, :status

  validates_presence_of :name
  validates_uniqueness_of :name

  has_and_belongs_to_many :suits

  mount_uploader :pic, PictureUploader

  def full_pic_url
    if self.pic and self.pic.url
      Rails.application.config.action_controller.asset_host + self.pic.url
    else
      ''
    end
  end

  def simple_json
    {
        lastestProductID: self.id.to_s,
        lastestProductName: self.name,
        lastestProductURL: full_pic_url
    }
  end

end

app/controllers/admin/new_products_controller.rb
class Admin::NewProductsController < Admin::BaseController
  load_and_authorize_resource

  def index
    @new_products = initialize_grid(NewProduct, order: 'rank', order_direction: 'asc', :per_page => 30)
  end

  def create
    @new_product = NewProduct.new(params[:new_product])
    if @new_product.save
      create_successfully
      redirect_to action: :index
    else
      fail_to_create
      render action: :new
    end
  end

  def update
    @new_product = NewProduct.find_by_id(params[:id])
    if @new_product.update_attributes(params[:new_product])
      update_successfully
      redirect_to action: :show
    else
      fail_to_update
      render action: :edit
    end
  end

  def destroy
    @new_product = NewProduct.find_by_id(params[:id])
    if @new_product.destroy
      destroy_successfully
    else
      fail_to_destroy
    end
    redirect_to action: :index
  end

  def modify
    authorize! :update, NewProduct
    if request.xml_http_request?
      res = false
      if (new_product = NewProduct.find_by_id(params[:id])) and new_product.respond_to?(params[:name])
        val = params[:value]
        val = val.to_i if 'rank' == params[:name]
        res = new_product.update_column(params[:name], val)
      end
      render json: {res: res, message: res ? t('admin.mess.update_successfully') : t('admin.mess.fail_to_update')}
    else
      raise ActionController::RoutingError.new('Not Found')
    end
  end

  def export
    authorize! :update, NewProduct
    respond_to do |format|
      format.html {

      }
      format.xlsx {
        @created_from = Cat::Tool.to_date(params[:from])
        @created_from = Date.today - 30.days if @created_from.nil?
        @created_to = Cat::Tool.to_date(params[:to], true)
        @suits = NewProduct.where('created_at >= ? and created_at < ?', @created_from.to_time.utc, (@created_to + 1.day).to_time.utc).order('id desc').all
        render xlsx: 'export', disposition: "attachment", layout: false, filename: "new_product_#{@created_from}_#{@created_to}"
      }
    end
  end
end

app/views/admin/new_products/_form.slim
- admin_left_menu :new_product
.page-header
  h4= title @new_product.new_record? ? '添加新品' : "修改新品 #{@new_product.name}"
.action-buttons
  - if @new_product.id
    = link_to '<i class="icon-briefcase icon-white"></i>'.html_safe, admin_new_product_suits_path(@new_product), class: 'btn btn-primary', title: '套装'
    = actions_buttons(@new_product, 1)

= simple_form_for @new_product, :url => (@new_product.new_record? ? admin_new_products_path : admin_new_product_path(@new_product)), :html => {class: 'form-horizontal'} do |f|
  fieldset
    = f.input :name
    = f.input :pic
    = f.input :rank, input_html: {class: 'input-small'}
    = f.input :status
    .form-actions
      = f.submit (@new_product.new_record? ? '保存' : '修改') , class: 'btn btn-primary', disable_with: '上传中，请稍等...'
- unless @new_product.new_record? or @new_product.full_pic_url.empty?
  h5 新品图标预览:
  p= image_tag(@new_product.full_pic_url)

app/views/admin/new_products/_grid.html.erb
<%= grid(@new_products, :show_filters => :when_filtered, :allow_showing_all_records => false, class: 'table-img') do |g|

  g.column do |obj|
    link_to(image_tag(obj.pic.thumb.url), obj.pic.url, target: '_blank') if obj.pic.url
  end

  %w(name).each do |attr|
    g.column :name => NewProduct.human_attribute_name(attr.to_sym), :attribute => attr do |obj|
      if attr.in? %w(created_at updated_at)
        t2l(obj.send(attr.to_sym))
      elsif attr == 'status'
        status_icon(obj.status)
      else
        obj.send(attr.to_sym)
      end
    end
  end

  g.column :name => '排序', :attribute => 'rank' do |obj|
    text = '<span class="edit-text">' + obj.rank.to_s + '</span><i class="icon-pencil"></i><input class="edit-input input-mini" name="rank" type="number" value="' + obj.rank.to_s + '">'
    [text.html_safe, {iid: obj.id, class: 'editable-blk'}]
  end


  %w(status created_at updated_at).each do |attr|
    g.column :name => NewProduct.human_attribute_name(attr.to_sym), :attribute => attr do |obj|
      if attr.in? %w(created_at updated_at)
        t2l(obj.send(attr.to_sym))
      elsif attr == 'status'
        status_icon(obj.status)
      else
        obj.send(attr.to_sym)
      end
    end
  end

  g.column do |obj|
    link = link_to '<i class="icon-briefcase"></i>'.html_safe, admin_new_product_suits_path(obj), title: '套装'
    link << actions_links(obj, 3)
  end
end -%>

app/views/admin/new_products/edit.slim
= new_product_breadcrumb @new_product
= render 'form'

app/views/admin/new_products/export.slim
- admin_left_menu :new_product
.page-header
  h4 导出新品数据

div
  form action="#{export_admin_new_products_path('xlsx')}" method="get" class="form-inline"
    p 根据新品创建的时间来导出数据。请选择创建时间：
    p
      | 从：
      input type="text" class="input-small" name="from" id="from"
      | &nbsp;&nbsp;到：
      input type="text" class="input-small" name="to" id="to"
      | &nbsp;&nbsp;&nbsp;&nbsp;
      button type="submit" class="btn btn-primary" 导出
- content_for :footer do
  javascript:
    $(document).ready(function(){el.Tool.datePicker();});

app/views/admin/new_products/index.slim
- admin_left_menu :new_product
.page-header
  h4= title '新品管理'
= render :partial => 'grid'
- content_for :footer do
  javascript:
    $(document).ready(function(){
      el.EditableTable.init("/admin/new_products/modify/");
    });

app/views/admin/new_products/show.slim
- title "新品-#{@new_product.name}"
- admin_left_menu :new_product
= new_product_breadcrumb @new_product
.action-buttons
  = link_to '<i class="icon-briefcase icon-white"></i>'.html_safe, admin_new_product_suits_path(@new_product), class: 'btn btn-primary', title: '套装'
  = actions_buttons(@new_product, 2)
table class="table table-striped"
  - NewProduct.attribute_names.each do |attr_name|
    tr
      th= NewProduct.human_attribute_name(attr_name)
      td
        - if 'pic' == attr_name
          = @new_product.pic.url.blank? ? '' : link_to(image_tag(@new_product.pic.thumb.url), @new_product.pic.url, target: '_blank')
        - elsif attr_name.in?(%w(created_at updated_at))
          = t2l(@new_product.send(attr_name.to_sym))
        - else
          = @new_product.send(attr_name.to_sym)