config/routes.rb
Cabbeen::Application.routes.draw do

  root :to => "home#index"

  def api_v1_routes
    namespace :v1 do
      resources :brand_info, :only => :index
      resources :city_weeklies, :only => :index
      resources :launch, :only => :create
      resources :lastest_see, :only => :index
      resources :products, :only => [:index, :show]
      resources :product_comments, :only => :create
      resources :shop_info, :only => :index
      resources :suits, :only => :index do
        collection do
          get 'search'
        end
      end
      resources :trend_couriers, :only => [:index, :show]
      resources :skins, :only => [:show, :index]
      resources :names, :only => [:index]
    end
  end

  def admin_routes

    devise_for :admins

    match '/admin' => redirect('/admins/sign_in')

    namespace :admin do

      resources :admins do
        collection do
          get 'edit_pwd' => 'admins#edit_pwd'
          put 'edit_pwd' => 'admins#update_pwd'
        end
      end

      resources :ads
      resources :brands
      resources :categories do
        resources :products
        collection do
          post 'modify/:id' => 'categories#modify'
        end
      end
      resources :city_weeklies do
        collection do
          get 'export'
        end
      end
      resources :dashboard, :only => :index
      resources :latest_sees do
        resources :pictures, :controller => :latest_see_pictures do
          collection do
            post 'modify/:id' => 'latest_see_pictures#modify'
          end
        end
        collection do
          get 'export'
        end
      end
      resources :new_products do
        resources :suits
        collection do
          post 'modify/:id' => 'new_products#modify'
          get 'export'
        end
      end
      resources :products do
        resources :comments, :controller => :product_comments
        resources :pictures, :controller => :product_pictures do
          collection do
            post 'modify/:id' => 'product_pictures#modify'
          end
        end
        resources :same_sections, :controller => :product_same_sections

        collection do
          get 'export'
          get 'export_comment' => 'product_comments#export'
          post 'batch_listed'
          post 'batch_unlisted'
          post 'batch_destroy'
          post 'batch_same_section'
          post 'modify/:id' => 'products#modify'
        end

      end
      get 'products_comments' => 'product_comments#index'

      resources :shop_infos
      resources :suits do
        collection do
          post 'modify/:id' => 'suits#modify'
          get 'export'
        end
        resources :products
      end

      resources :skins
      resources :trend_couriers do
        resources :products
        collection do
          get 'export'
        end
      end
    end
  end

  api_v1_routes
  admin_routes

end

app/models/product.rb
# encoding: utf-8
class Product < ActiveRecord::Base
  attr_accessible :description, :serial_number, :trend_courier_id, :status, :title,
                  :category_ids, :suit_ids, :sub_title, :is_top, :price, :design_inspiration, :color_pic, :summary,
                  :suit_category, :time_for_sale, :color_name, :rank

  mount_uploader :color_pic, PictureUploader

  validates_presence_of :serial_number
  validates_uniqueness_of :serial_number

  belongs_to :trend_courier
  has_and_belongs_to_many :categories
  has_and_belongs_to_many :suits
  has_many :product_pictures, :dependent => :destroy
  has_many :product_comments, :dependent => :destroy

  has_many :product_same_sections, :dependent => :destroy

  before_destroy :clean_same_section

  def self.suit_categories
    {
        '上装' => 1,
        '内搭' => 2,
        '外套' => 3,
        '下装' => 4,
        '鞋子' => 5,
        '配饰' => 6
    }
  end

  def suit_category_name
    res = ''
    Product.suit_categories.map do |name, id|
      if self.suit_category == id
        res = name
        break
      end
    end
    res
  end

  def simple_json
    {
        proID: self.id.to_s,
        proSerialNumber: self.serial_number,
        proTitle: Cat::Tool.nil2n(self.title),
        proSubTitle: Cat::Tool.nil2n(self.sub_title),
        proRank: self.rank.to_i,
        proPrice: Cat::Tool.nil2n(self.price),
        createTime: self.created_at.to_s,
        updateTime: self.updated_at.to_s,
        proExplainText: Cat::Tool.nil2n(self.description),
        proDesignInspiration: Cat::Tool.nil2n(self.design_inspiration),
        proColorName: Cat::Tool.nil2n(self.color_name),
        proColorImageURL: full_color_pic_url,
        proTrendCourierID: self.trend_courier_id.to_s,
        proTrendCourierUrl: self.trend_courier ? self.trend_courier.full_pic_url : '',
        proImageURLArray: picture_urls,
        proSimpleIntroduce: Cat::Tool.nil2n(self.summary),
        timeForSale: Cat::Tool.nil2n(self.time_for_sale),
        proSuitCategoryID: self.suit_category.to_s,
        proSuitCategoryName: suit_category_name
    }
  end

  def full_color_pic_url
    if self.color_pic and self.color_pic.url
      Rails.application.config.action_controller.asset_host + self.color_pic.url
    else
      ''
    end
  end

  def picture_urls
    res = []
    self.product_pictures.order('rank ASC, id ASC').each do |pic|
      res << pic.full_pic_url
    end
    res
  end

  def same_sections
    res = []
    ProductSameSection.where(p_id: self.id).order('id ASC').each do |section|
      _product = section.product
      if _product and _product.status?
        res << _product.simple_json
      end
    end
    res
  end

  private

  def clean_same_section
    ProductSameSection.destroy_all(p_id: self.id)
  end
end

app/controllers/admin/products_controller.rb
# encoding: utf-8
class Admin::ProductsController < Admin::BaseController
  load_and_authorize_resource

  def index
    if params[:category_id] and (@category = Category.find_by_id(params[:category_id]))
      @products = initialize_grid(Product, conditions: {id: @category.products.limit(1000).pluck(:product_id)}, order: 'id', order_direction: 'desc')
    elsif params[:suit_id] and (@suit = Suit.find_by_id(params[:suit_id]))
      @products = initialize_grid(Product, conditions: {id: @suit.products.limit(1000).pluck(:product_id)}, order: 'id', order_direction: 'desc')
    elsif params[:trend_courier_id] and (@trend_courier = TrendCourier.find_by_id(params[:trend_courier_id]))
      @products = initialize_grid(Product, conditions: {trend_courier_id: @trend_courier.id}, order: 'id', order_direction: 'desc')
    else
      @products = initialize_grid(Product, order: 'id', order_direction: 'desc')
    end
    @title_prefix = "“#{@title_prefix}”的" unless @title_prefix.blank?
  end

  def export
    authorize! :update, Product
    respond_to do |format|
      format.html {

      }
      format.xlsx {
        @created_from = Cat::Tool.to_date(params[:from])
        @created_from = Date.today - 30.days if @created_from.nil?
        @created_to = Cat::Tool.to_date(params[:to], true)
        @products = Product.where('created_at >= ? and created_at < ?', @created_from.to_time.utc, (@created_to + 1.day).to_time.utc).order('id desc').all
        render xlsx: 'export', disposition: "attachment", layout: false, filename: "product_#{@created_from}_#{@created_to}"
      }
    end
  end

  def new
    if (pro = Product.last)
      rank = pro.id.to_i + 1
    else
      rank = 1
    end
    @product = Product.new(rank: rank)
  end

  def create
    @product = Product.new(params[:product])
    if @product.save
      flash[:success] = '请继续上传单品图片'
      redirect_to admin_product_pictures_path(@product)
    else
      fail_to_create
      render action: :new
    end
  end

  def update
    @product = Product.find_by_id(params[:id])
    if @product.update_attributes(params[:product])
      update_successfully
      redirect_to action: :show
    else
      fail_to_update
      render action: :edit
    end
  end

  def destroy
    if (@product = Product.find_by_id(params[:id]))
      if params[:category_id]
        if (@category = Category.find_by_id(params[:category_id]))
          @category.products.delete(@product)
        end
      elsif params[:suit_id]
        if  (@suit = Suit.find_by_id(params[:suit_id]))
          @suit.products.delete(@product)
        end
      elsif params[:trend_courier_id]
        if (@trend_courier = TrendCourier.find_by_id(params[:trend_courier_id]))
          @product.update_column(:trend_courier_id, nil)
        end
      else
        @product.destroy
      end
      destroy_successfully
    else
      fail_to_destroy
    end
    redirect_to action: :index
  end

  def batch_unlisted
    render json: Logic::ProductTool.batch_listed(params, 0), status: :ok
  end

  def batch_listed
    render json: Logic::ProductTool.batch_listed(params, 1), status: :ok
  end

  def batch_destroy
    render json: Logic::ProductTool.batch_destroy(params), status: :ok
  end

  def batch_same_section
    render json: Logic::ProductTool.batch_set_same_section(params), status: :ok
  end

  def modify
    authorize! :update, Product
    if request.xml_http_request?
      res = false
      if (product = Product.find_by_id(params[:id])) and product.respond_to?(params[:name])
        val = params[:value]
        val = val.to_i if 'rank' == params[:name]
        res = product.update_column(params[:name], val)
      end
      render json: {res: res, message: res ? t('admin.mess.update_successfully') : t('admin.mess.fail_to_update')}
    else
      raise ActionController::RoutingError.new('Not Found')
    end
  end

end

app/controllers/v1/products_controller.rb
class V1::ProductsController < V1::BaseController

  def index
    render json: Logic::ProductTool.products_json(params), status: :ok
  end

  def show
    render json: Logic::ProductTool.product_json(params), status: :ok
  end
end

app/views/admin/products/_form.slim
- admin_left_menu :product
.page-header
  h4= title @product.new_record? ? '添加单品' : "修改单品 #{@product.title}"
.action-buttons
  -if @product.id
    = cc_link_to '<i class="icon-picture icon-white"></i>'.html_safe, admin_product_pictures_path(@product), title: '图片', class: 'btn btn-primary', cc: [:read, ProductPicture, display: false]
    = cc_link_to '<i class="icon-list-alt icon-white"></i>'.html_safe, admin_product_same_sections_path(@product), title: '同款', class: 'btn btn-primary', cc: [:read, ProductSameSection, display: false]
    = cc_link_to '<i class="icon-comment icon-white"></i>'.html_safe, admin_product_comments_path(@product), title: '评价', class: 'btn btn-primary', cc: [:read, ProductComment, display: false]
    = actions_buttons(@product, 5)
= simple_form_for @product, :url => (@product.new_record? ? admin_products_path : admin_product_path(@product)), :html => {class: 'form-horizontal'} do |f|
  fieldset
    = f.input :serial_number, input_html: {class: 'input-xlarge', autocomplete: 'off'}
    = f.input :title, input_html: {class: 'input-xxlarge'}
    = f.input :sub_title, input_html: {class: 'input-xxlarge', autocomplete: 'off', "data-provide" => "typeahead", "data-source"=>'["SHIRT","T-SHIRT","KNITWEAR","SWEATER","BLAZER","DOWN COAT","PADDED COAT","LEATHER JACKET","JACKET","COAT","VEST","DOWN VEST","PANT","TROUSER","CASUAL PANT","CASUAL TROUSER","JEANS","SHORT","SUITS","SUIT JACKET","SUIT PANT","SUIT TROUSER","SHOES","LEATHER SHOES","CASUAL SHOES","BAG","BELT","TIE","UNDERWEAR","SOCKS","SCARF"]'}
    = f.input :suit_category, collection: Product.suit_categories, input_html: {class: 'input-small'}
    = f.association :trend_courier
    = f.association :categories, collection: Category.order('id DESC').limit(5000), input_html: {class: 'span7', style: "height: 150px;"}
    = f.association :suits, collection: Suit.select('id, serial_number').order('id DESC').limit(10000), input_html: {class: 'span7', style: "height: 150px;"}, label_method: :serial_number, value_method: :id
    = f.input :price, input_html: {class: 'input-small'}
    = f.input :rank
    = f.input :time_for_sale
    = f.input :color_name
    = f.input :color_pic
    - unless @product.full_color_pic_url.empty?
      .control-group
        .control-label &nbsp;
        .controls= image_tag(@product.full_color_pic_url, style: 'max-width: 50px')
    = f.input :summary, input_html:{class: 'input-xxlarge', style: "height: 60px"}
    = f.input :description, input_html:{class: 'input-xxlarge', style: "height: 100px"}
    = f.input :design_inspiration, input_html:{class: 'input-xxlarge', style: "height: 100px"}
    = f.input :status
    .form-actions
      = f.submit (@product.new_record? ? '下一步，上传图片' : '修改') , class: 'btn btn-primary', disable_with: '保存中，请稍等...'

- content_for :footer do
  = javascript_include_tag 'multiselect'
  javascript:
    $(document).ready(function(){
      $('#product_time_for_sale').datepicker({dateFormat: 'yy-mm-dd'});
      $('#product_suit_ids').multiselect({locale: 'zh','searchField': true});
      $('#product_category_ids').multiselect({locale: 'zh','searchField': true});
    });

app/views/admin/products/_grid.html.erb
<%= grid(@products, show_filters: :when_filtered, allow_showing_all_records: false, class: 'table-img') do |g|

  g.column name: '<input type="checkbox" class="select_all_or_cancel"/>'.html_safe do |obj|
    "<input type='checkbox' name='ids[]' value='#{obj.id}'/>".html_safe
  end

  g.column do |obj|
    if obj.product_pictures.count > 0 and '' != obj.product_pictures.first.thumb_full_pic_url
      link_to(image_tag(obj.product_pictures.first.thumb_full_pic_url), obj.product_pictures.first.full_pic_url, target: '_blank')
    end
  end

  %w(id serial_number title price).each do |attr|
    g.column :name => Product.human_attribute_name(attr.to_sym), :attribute => attr do |obj|
      if attr == 'is_top'
        obj.is_top ? '是' : '否'
      elsif attr == 'trend_courier_id'
        obj.trend_courier.title if obj.trend_courier
      else
        obj.send(attr.to_sym)
      end
    end
  end

  g.column :name => '排序', :attribute => 'rank' do |obj|
    text = '<span class="edit-text">' + obj.rank.to_s + '</span><i class="icon-pencil"></i><input class="edit-input input-mini" name="rank" type="number" value="' + obj.rank.to_s + '">'
    [text.html_safe, {iid: obj.id, class: 'editable-blk'}]
  end

  %w(status created_at).each do |attr|
    g.column :name => Product.human_attribute_name(attr.to_sym), :attribute => attr do |obj|
      if attr.in? %w(created_at updated_at)
        t2l(obj.send(attr.to_sym))
      elsif attr == 'status'
        status_icon(obj.status)
      else
        obj.send(attr.to_sym)
      end
    end
  end

  g.column do |obj|
    if obj.product_pictures.count == 0
      link = link_to('<i class="icon-picture" title="图片"></i>'.html_safe, admin_product_pictures_path(obj.id, t: Time.now.to_i))
    else
      link = link_to('<i class="icon-picture" title="图片"></i>'.html_safe, admin_product_pictures_path(obj.id))
    end
    link << link_to('<i class="icon-list-alt" title="同款"></i>'.html_safe, admin_product_same_sections_path(obj.id))
    link << link_to('<i class="icon-comment" title="评价"></i>'.html_safe, admin_product_comments_path(obj.id))
    if @category or @suit or @trend_courier
      link << actions_links(obj, 3)
      if @category
        link << link_to('<i class="icon-remove"></i>'.html_safe, admin_category_product_path(@category.id, obj.id), method: :delete, data: {confirm: "确定将单品#{obj.id}从品类#{@category.name}中删除"}, title: "将单品#{obj.id}从品类#{@category.name}中删除")
      elsif @suit
        link << link_to('<i class="icon-remove"></i>'.html_safe, admin_suit_product_path(@suit.id, obj.id), method: :delete, data: {confirm: "确定将单品#{obj.id}从套装#{@suit.title}中删除？"}, title: "将单品#{obj.id}从套装#{@suit.title}中删除")
      elsif @trend_courier
        link << link_to('<i class="icon-remove"></i>'.html_safe, admin_trend_courier_product_path(@trend_courier.id, obj.id), method: :delete, data: {confirm: "确定将单品#{obj.id}从潮流速递#{@trend_courier.title}中删除？"}, title: "将单品#{obj.id}从潮流速递#{@trend_courier.title}中删除")
      end
    else
      link << actions_links(obj, 7)
    end
    link.html_safe
  end

end -%>

app/views/admin/products/edit.slim
= product_breadcrumb @product
= render 'form'

app/views/admin/products/export.slim
- admin_left_menu :product
.page-header
  h4 导出单品数据

div
  form action="#{export_admin_products_path('xlsx')}" method="get" class="form-inline"
    p 根据单品创建的时间来导出数据。请选择创建时间：
    p
      | 从：
      input type="text" class="input-small" name="from" id="from"
      | &nbsp;&nbsp;到：
      input type="text" class="input-small" name="to" id="to"
      | &nbsp;&nbsp;&nbsp;&nbsp;
      button type="submit" class="btn btn-primary" 导出
- content_for :footer do
  javascript:
    $(function() {
      $( "#from" ).datepicker({
        dateFormat: "yy-mm-dd",
        defaultDate: "-1m",
        numberOfMonths: 2,
        onClose: function( selectedDate ) {
          $( "#to" ).datepicker( "option", "minDate", selectedDate );
        }
      });
      $( "#to" ).datepicker({
        dateFormat: "yy-mm-dd",
        defaultDate: "-1d",
        numberOfMonths: 1,
        onClose: function( selectedDate ) {
          $( "#from" ).datepicker( "option", "maxDate", selectedDate );
        }
      });
    });

app/views/admin/products/index.slim
- admin_left_menu :product
.page-header
  - if @category
    h4
      | 品类
      = link_to @category.name, admin_category_path(@category.id)
      | 的单品
  - elsif @suit
    h4
      | 套装
      = link_to @suit.title, admin_suit_path(@suit.id)
      | 的单品
  - elsif @trend_courier
    h4
      | 潮流速递
      = link_to @trend_courier.title, admin_trend_courier_path(@trend_courier.id)
      | 的单品
  - else
    h4= title '单品管理'
= render :partial => 'grid'
.batch-opt-div
  label style="display: inline-block"
    input type="checkbox" class="select_all_or_cancel"
    | &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  .btn-group
    button.btn.btn-small.btn-primary.batch_same_section
      i.icon-list-alt.icon-white title="设置为同款"
      | 设置同款
    button.btn.btn-small.btn-info.batch_listed title="批量上架"
      i.icon-ok-circle.icon-white
      | 上架
    button.btn.btn-small.btn-info.batch_unlisted title="批量下架"
      i.icon-ban-circle.icon-white
      | 下架
    - unless @category or @suit or @trend_courier
      button.btn.btn-small.btn-danger.batch_destroy title="批量删除"
        i.icon-remove.icon-white
        | 删除
javascript:
  $(document).ready(function () {
    el.Product.init();
    el.EditableTable.init("/admin/products/modify/");
  });

app/views/admin/products/show.slim
- title "单品-#{@product.title}"
- admin_left_menu :product
= product_breadcrumb @product
.action-buttons
  = cc_link_to '<i class="icon-picture icon-white"></i>'.html_safe, admin_product_pictures_path(@product), title: '图片', class: 'btn btn-primary', cc: [:read, ProductPicture, display: false]
  = cc_link_to '<i class="icon-list-alt icon-white"></i>'.html_safe, admin_product_same_sections_path(@product), title: '同款', class: 'btn btn-primary', cc: [:read, ProductSameSection, display: false]
  = cc_link_to '<i class="icon-comment icon-white"></i>'.html_safe, admin_product_comments_path(@product), title: '评价', class: 'btn btn-primary', cc: [:read, ProductComment, display: false]
  = actions_buttons(@product, 6)
table class="table table-striped"
  - Product.attribute_names.each do |attr_name|
    - next if attr_name == 'is_top'
    tr
      th= Product.human_attribute_name(attr_name)
      td
        - if 'color_pic' == attr_name
          = @product.full_color_pic_url.blank? ? '' : link_to(image_tag(@product.color_pic.thumb.url), @product.full_color_pic_url, target: '_blank')
        - elsif 'trend_courier_id' == attr_name
          - if @product.trend_courier
            = link_to @product.trend_courier.title, admin_trend_courier_path(@product.trend_courier_id)
        - elsif attr_name.in?(%w(created_at updated_at))
          = t2l(@product.send(attr_name.to_sym))
        - elsif attr_name == 'suit_category'
          = @product.suit_category_name
        - else
          = @product.send(attr_name.to_sym)
  tr
    th 品类
    td
      - @product.categories.each do |category|
        = link_to category.name, admin_category_path(category.id), target: '_blank'
        | &nbsp;&nbsp;
  tr
    th 套装
    td
      - @product.suits.each do |suit|
        = link_to suit.title, admin_suit_path(suit.id), target: '_blank'
        | &nbsp;&nbsp;
  tr
    th 图片缩略图
    td
      - @product.product_pictures.each do | pic |
        - if '' != pic.thumb_full_pic_url
          = link_to(image_tag(pic.thumb_full_pic_url), pic.full_pic_url, target: '_blank')
          | &nbsp; &nbsp;